### ISSUE TITLE
Over-aggressive Glyph Caching

### ISSUE THREAD

**Issue by szos** [dmb2/clx-ft2-renderer#2]
The function `cache-char` only renders a glyph if it doesn't exist in the hash table. This leads to issues with spacing and glyph size if a user changes the size of their font. 

Steps to reproduce: 

```lisp
(in-package :stumpwm)
(set-font (list (make-instance 'clx-ft2:font 
                               :family "DejaVu Sans Mono"
                               :size 12)))
;; Wait for strings to render (eg in the mode line)
(set-font (list (make-instance 'clx-ft2:font 
                               :family "DejaVu Sans Mono"
                               :size 16)))
;; See that the glyph size hasnt changed, but the font spacing has. 
```

The simple brute-force solution is to render every glyph every time. A better solution (imo) would be to store a glyph cache per font object, so that by instantiating a new font object the cache would be effectively cleared and new glyphs would be rendered. I'm unsure how much work it would be to do that, but i'm looking into it.

**Comment by PuercoPop** [comment]
> A better solution (imo) would be to store a glyph cache per font object

By per font object you mean a different cache for each font configuration? ie. The cache key would include font-size, family, style, underline, etc?

**Comment by szos** [comment]
Kind of - i opened a PR implementing this, wherin each font object carries with it a cache hash table which gets used instead of `*ft2-face-cache*`.
